version: "3.7"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - 3001:80
    environment:
      - REACT_APP_API_URL=http://localhost:3002
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3002:80